version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portal-breeze-app
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "5173:5173"
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: portal-breeze-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: portal-breeze-db
    restart: always
    environment:
      MYSQL_DATABASE: authbreeze
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: